library(grpreg)
library(grplasso)
library(microbenchmark)
library(bcd)
library(Matrix)

set.seed(33)
tol=10^-8
tolGrp=10^-11
k=1
n=5000
p=30
X=matrix(rnorm(n*p),n,p)
X[,1]=rep(1,n)
beta=rnorm(p)
groups=list(1,2:5,6:15,16:20,21:22,23:25,26:30)
groupLengths=sapply(groups,length)
groupStart=c(0,cumsum(groupLengths[1:(length(groups)-1)]))
groupEnd=cumsum(groupLengths)-1
groupColumns=unlist(groups)-1
beta=rnorm(length(groupColumns)*k)
beta[21:22]=0
beta[26:30]=0
penaltyFactor=c(0,1,1,1,1,1,1)
sampleWeights=rep(1,n)
XSparse=Matrix(X,sparse=TRUE)
response=rnorm(n)+X%*%beta
test=multiResponseGaussianDense(length(groups)
                                ,groupStart
                                ,groupEnd
                                ,groupColumns
                                ,tol
                                ,penaltyFactor
                                ,1000
                                ,response
                                ,X
                                ,1
                                ,1)

testSparse=multiResponseGaussianSparse(length(groups)
                                       ,groupStart
                                       ,groupEnd
                                       ,groupColumns
                                       ,tol
                                       ,penaltyFactor
                                       ,1000
                                       ,response
                                       ,XSparse
                                       ,1
                                       ,1)
fitreg=grpreg(X[,2:dim(X)[2]],response,group=c(rep(1,4),rep(2,10),rep(3,5),rep(4,2),rep(5,3),rep(6,5)),eps=tolGrp)
